//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_TW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_TW() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickStart.Resources.Resource_zh-TW", typeof(Resource_zh_TW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 關閉 的本地化字符串。
        /// </summary>
        internal static string aboutForm_BtnClose_Text {
            get {
                return ResourceManager.GetString("aboutForm_BtnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關於 的本地化字符串。
        /// </summary>
        internal static string aboutForm_Title_Text {
            get {
                return ResourceManager.GetString("aboutForm_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關於 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_About_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_Display_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Display_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_Exit_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 語言 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_Language_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文(簡體) 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_LanguageChineseSimplified_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageChineseSimplified_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文(繁體) 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_LanguageChineseTraditional_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageChineseTraditional_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英語 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_LanguageEnglish_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageEnglish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_LanguageJapanese_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageJapanese_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韓語 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_LanguageKorean_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageKorean_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不透明度 的本地化字符串。
        /// </summary>
        internal static string toolStripMenuItem_Opacity_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Opacity_Text", resourceCulture);
            }
        }
    }
}
