//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en_US() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickStart.Resources.Resource_en-US", typeof(Resource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string aboutForm_BtnClose_Text {
            get {
                return ResourceManager.GetString("aboutForm_BtnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string aboutForm_Title_Text {
            get {
                return ResourceManager.GetString("aboutForm_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_About_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_Display_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Display_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_Exit_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_Language_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chinese(Simplified) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_LanguageChineseSimplified_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageChineseSimplified_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chinese(Traditional) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_LanguageChineseTraditional_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageChineseTraditional_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_LanguageEnglish_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageEnglish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_LanguageJapanese_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageJapanese_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_LanguageKorean_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_LanguageKorean_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_Opacity_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Opacity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Form Dock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_Timer_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_Timer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_TimerOff_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_TimerOff_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolStripMenuItem_TimerOn_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem_TimerOn_Text", resourceCulture);
            }
        }
    }
}
